package com.lockOnActive
import com.secbro.drools.model.Person

rule "test-lock-on-active-1"

when

    $p : Person( age < 20)
then
    System.out.println("test-lock-on-active-1 被触发,age=" + $p.getAge());
    $p.setAge(21);
    update($p)
 end

rule "test-lock-on-active-2"
lock-on-active true
when
    $p : Person(age > 20)
then
    System.out.println("test-lock-on-active-2 被触发,age=" + $p.getAge());

end