package com.firstspace.firstproject.entity;

import org.kie.api.definition.type.Description;
import org.kie.api.definition.type.Label;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class User implements Serializable {

	static final long serialVersionUID = 1L;

	@Label(value = "ID")
	private Integer id;

	@Label(value = "用户名")
	private String username;

	@Description(value = "age > 18 && age < 60")
	@Label(value = "年龄")
	private Integer age;

	public User() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public User(Integer id, String username,
	            Integer age) {
		this.id = id;
		this.username = username;
		this.age = age;
	}

}