package com.testspace.firstproject.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserCheckResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "结果编码（PASS或NOT-PASS）")
	private java.lang.String code;
	@org.kie.api.definition.type.Label(value = "信息描述")
	private java.lang.String message;

	public UserCheckResult() {
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public UserCheckResult(java.lang.String code, java.lang.String message) {
		this.code = code;
		this.message = message;
	}

}