package com.testspace.firstproject.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID")
	private Integer id;
	@org.kie.api.definition.type.Label(value = "用户名")
	private String username;
	@org.kie.api.definition.type.Label(value = "年龄")
	private Integer age;

	public User() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getUsername() {
		return this.username;
	}

	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public User(java.lang.Integer id, java.lang.String username,
	            java.lang.Integer age) {
		this.id = id;
		this.username = username;
		this.age = age;
	}

}