package com.conditional
import com.secbro.drools.model.Person
import com.secbro.drools.model.Car

rule "conditional-test-rule-1"
no-loop true
when
    $p : Person(age > 18)
    if (age == 20) do[updatePerson]
    else do[updatePerson1]
then

    System.out.println("规则conditional-test-rule-1 被触发");

then[updatePerson]
    System.out.println("执行updatePerson");
    modify($p){
        setAge(17)
    }
then[updatePerson1]
    System.out.println("执行updatePerson1");
    modify($p){
        setAge(21)
    }
end



rule "conditional-test-rule-2"
        extends "conditional-test-rule-1"

when
//    $p : Person(age > 18);
    $car : Car(discount < 90);
then
    System.out.println("规则conditional-test-rule-2 被触发");
end